name: Test successive invocations
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        commands: |
          echo "First invocation"
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        commands: |
          echo "Second invocation"
