name: Test artifact copy
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        copy_artifact_path: artifact
        commands: |
            touch artifact
    - name: Test artifact was copied
      run: |
        test -f artifact
