name: Test import_github_env with bash
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "VARNAME=value" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        import_github_env: true
        shell: bash
        commands: |
          [ -n "${VARNAME}" ]
