name: Test armv7l cpu option
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        cpu: cortex-a8
        commands: |
            echo "Minimal"
            test `uname -m` = 'armv7l'
