name: Test default cpu option
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_image: ["raspios_lite:latest", "raspios_lite_arm64:latest"]
        include:
        - base_image: raspios_lite:latest
          arch: armv6l
        - base_image: raspios_lite_arm64:latest
          arch: aarch64
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        base_image: ${{ matrix.base_image }}
        commands: |
            echo "Minimal"
            test `uname -m` = ${{ matrix.arch }}
