name: Test sudo with pi
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        commands: |
            echo 'pi ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/010_pi-nopasswd
            sudo chmod 0440 /etc/sudoers.d/010_pi-nopasswd
            sudo -u pi /bin/bash -c 'sudo echo hello'
