name: Test import_github_env
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "VARNAME=value" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        import_github_env: true
        commands: |
          [ -n "${VARNAME}" ]
