name: Test bind mount
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        bind_mount_repository: true
        commands: |
            uname -m > artifact
    - name: Test created file persists
      run: |
        test -f artifact
        test `cat artifact` = 'armv6l'
