name: Test debug on
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@HEAD
      with:
        debug: true
        commands: |
          set -o | egrep 'xtrace\s+on'
