name: Test exit_on_fail
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        exit_on_fail: false
        commands: |
          false
          exit 0
