name: Test export_github_env
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@HEAD
      with:
        export_github_env: true
        commands: |
          echo "VARNAME=value" >> $GITHUB_ENV
    - run: |
        [ -n "${VARNAME}" ]
