name: Test systemd-nspawn
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        use_systemd_nspawn: true
        commands: |
          uname -a
