name: Test appimage aarch64
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      with:
        cpu: cortex-a53
        base_image: raspios_lite_arm64:latest
        commands: |
            sudo apt install libfuse2 -y
            wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-aarch64.AppImage
            chmod +x appimagetool-aarch64.AppImage
            ./appimagetool-aarch64.AppImage --version
